### PR TITLE
Mooreds/initial example

### PR DESCRIPTION
**Pull request by mooreds**
This is the initial code push of a QR login example.

### CODE REVIEW

**Comment by synedra** [comment]
A couple of minor suggestions and then an actual problem:
- A pointer to ngrok would be great along with a quick description
- An example of the config file with the ngrok URLs would help - I wasn't sure which direction to go

I think I got the kickstart stuff right, but while the landing page for the app works on my phone, the login button doesn't work.  On the python/flask server side I see:

raceback (most recent call last):
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/server.py", line 139, in login
    return oauth.FusionAuth.authorize_redirect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/authlib/integrations/flask_client/apps.py", line 43, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/authlib/integrations/base_client/sync_app.py", line 309, in create_authorization_url
    metadata = self.load_server_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/authlib/integrations/base_client/sync_app.py", line 295, in load_server_metadata
    resp.raise_for_status()
  File "/Users/synedra/dev/inversoft/fusionauth/fusionauth-example-qr-codes/venv/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://d9d5-73-249-72-110.ngrok-free.app/.well-known/openid-configuration
127.0.0.1 - - [08/Aug/2024 09:17:44] "GET /login HTTP/1.1" 500 -

And I get an Internal Server Error on the phone.

**Review by synedra — COMMENTED** [review]
After an initial hiccup, it all worked smoothly.  Looks good to me!

**Comment by mooreds** [comment]
@synedra can you please explicitly approve this? A comment isn't enough to let me merge :(

**Review by synedra — APPROVED** [review]

**Comment by mooreds** [comment]
Weird, it still won't let me merge without overriding,

**Pull request merged**
